-- Seed mock user profiles for testing and demonstration
-- Note: These are profile-only entries without auth credentials
-- They will appear in the matches/discovery section but cannot log in

-- Disable RLS temporarily to ensure mock profiles can be inserted
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;

-- Drop foreign key constraint temporarily to allow mock profiles
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- Delete existing mock users to allow re-running the script
DELETE FROM public.profiles WHERE email LIKE '%@example.com';

INSERT INTO public.profiles (
  id,
  email,
  full_name,
  display_name,
  avatar_url,
  bio,
  skill_level,
  average_handicap,
  interests,
  match_goals,
  personality_traits,
  play_frequency,
  preferred_round_time,
  pace_of_play,
  swing_tendency,
  group_preference,
  trust_score,
  total_rounds,
  completed_rounds,
  created_at,
  updated_at
) VALUES
    (
      '11111111-1111-1111-1111-111111111111'::uuid,
      'sarah.chen@example.com',
      'Sarah Chen',
      'Sarah C.',
      null,
      'Competitive golfer looking to improve my game. Love early morning rounds and challenging courses. Always up for a friendly match!',
      'advanced',
      8.5,
      ARRAY['Competitive Play', 'Tournament Play', 'Skill Improvement'],
      ARRAY['sharpen skills', 'compete seriously'],
      ARRAY['competitive', 'focused', 'disciplined'],
      'multiple_per_week',
      'morning',
      'fast',
      'right',
      'twosome',
      95,
      45,
      42,
      now(),
      now()
    ),
    (
      '22222222-2222-2222-2222-222222222222'::uuid,
      'mike.johnson@example.com',
      'Mike Johnson',
      'Mike J.',
      null,
      'Golf is my favorite way to unwind and meet new people. More about the experience than the score. Let''s have fun out there!',
      'intermediate',
      15.2,
      ARRAY['Casual Rounds', 'Social Networking', 'Weekend Warrior'],
      ARRAY['meet new people', 'relax outdoors'],
      ARRAY['sociable', 'supportive', 'easygoing'],
      'weekly',
      'afternoon',
      'relaxed',
      'left',
      'foursome',
      100,
      32,
      30,
      now(),
      now()
    ),
    (
      '33333333-3333-3333-3333-333333333333'::uuid,
      'emily.rodriguez@example.com',
      'Emily Rodriguez',
      'Emily R.',
      null,
      'New to golf and loving it! Looking for patient partners who don''t mind a few extra swings. Always eager to learn.',
      'beginner',
      28.0,
      ARRAY['Skill Improvement', 'Casual Rounds', 'Social Networking'],
      ARRAY['learn fundamentals', 'meet new people'],
      ARRAY['patient', 'encouraging', 'supportive'],
      'twice_per_month',
      'morning',
      'steady',
      'right',
      'flexible',
      100,
      12,
      12,
      now(),
      now()
    ),
    (
      '44444444-4444-4444-4444-444444444444'::uuid,
      'david.kim@example.com',
      'David Kim',
      'David K.',
      null,
      'Single-digit handicap player. Play in local tournaments and always looking to sharpen my skills. Serious about the game but friendly on the course.',
      'expert',
      4.2,
      ARRAY['Competitive Play', 'Tournament Play', 'Skill Improvement'],
      ARRAY['compete seriously', 'sharpen skills'],
      ARRAY['competitive', 'focused', 'confident'],
      'multiple_per_week',
      'morning',
      'fast',
      'straight',
      'twosome',
      98,
      120,
      115,
      now(),
      now()
    ),
    (
      '55555555-5555-5555-5555-555555555555'::uuid,
      'jessica.taylor@example.com',
      'Jessica Taylor',
      'Jess T.',
      null,
      'Golf is my cardio! Love walking the course and staying active. Looking for partners who enjoy a brisk pace and healthy lifestyle.',
      'intermediate',
      16.8,
      ARRAY['Weekend Warrior', 'Casual Rounds', 'Skill Improvement'],
      ARRAY['stay active', 'meet new people'],
      ARRAY['energetic', 'supportive', 'sociable'],
      'weekly',
      'midday',
      'steady',
      'left',
      'foursome',
      100,
      38,
      36,
      now(),
      now()
    ),
    (
      '66666666-6666-6666-6666-666666666666'::uuid,
      'alex.patel@example.com',
      'Alex Patel',
      'Alex P.',
      null,
      'Business development professional who loves golf for networking and building relationships. Great conversations, good golf, better connections.',
      'intermediate',
      14.5,
      ARRAY['Business Networking', 'Social Networking', 'Casual Rounds'],
      ARRAY['host clients', 'meet new people'],
      ARRAY['strategic', 'confident', 'sociable'],
      'twice_per_month',
      'afternoon',
      'steady',
      'right',
      'foursome',
      100,
      55,
      52,
      now(),
      now()
    ),
    (
      '77777777-7777-7777-7777-777777777777'::uuid,
      'rachel.wong@example.com',
      'Rachel Wong',
      'Rachel W.',
      null,
      'Just started playing this year and absolutely hooked! Taking lessons and practicing regularly. Would love to play with others who are learning too.',
      'beginner',
      32.0,
      ARRAY['Skill Improvement', 'Casual Rounds', 'Course Exploration'],
      ARRAY['learn fundamentals', 'stay active'],
      ARRAY['patient', 'encouraging', 'analytical'],
      'monthly',
      'morning',
      'steady',
      'right',
      'flexible',
      100,
      8,
      8,
      now(),
      now()
    ),
    (
      '88888888-8888-8888-8888-888888888888'::uuid,
      'james.anderson@example.com',
      'James Anderson',
      'James A.',
      null,
      'Been playing for 20+ years. Love the social aspect of golf and meeting new people. Happy to share tips with newer players!',
      'advanced',
      9.8,
      ARRAY['Social Networking', 'Casual Rounds', 'Skill Improvement'],
      ARRAY['meet new people', 'mentor others'],
      ARRAY['supportive', 'easygoing', 'sociable'],
      'weekly',
      'midday',
      'steady',
      'straight',
      'foursome',
      100,
      200,
      190,
      now(),
      now()
    ),
    (
      '99999999-9999-9999-9999-999999999999'::uuid,
      'maria.garcia@example.com',
      'Maria Garcia',
      'Maria G.',
      null,
      'Weekend warrior who plays for fun and relaxation. Not too serious about scores, just enjoy being outdoors and good company.',
      'intermediate',
      18.5,
      ARRAY['Casual Rounds', 'Course Exploration', 'Weekend Warrior'],
      ARRAY['relax outdoors', 'stay active'],
      ARRAY['easygoing', 'supportive', 'energetic'],
      'twice_per_month',
      'afternoon',
      'relaxed',
      'left',
      'foursome',
      100,
      28,
      26,
      now(),
      now()
    ),
    (
      'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'::uuid,
      'tom.wilson@example.com',
      'Tom Wilson',
      'Tom W.',
      null,
      'Working hard to break into single digits. Play in club tournaments and always looking for competitive rounds. Let''s push each other!',
      'intermediate',
      12.3,
      ARRAY['Competitive Play', 'Skill Improvement', 'Tournament Play'],
      ARRAY['compete seriously', 'sharpen skills'],
      ARRAY['competitive', 'disciplined', 'focused'],
      'weekly',
      'morning',
      'fast',
      'right',
      'twosome',
      95,
      65,
      60,
      now(),
      now()
    ),
    (
      'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid,
      'lisa.brown@example.com',
      'Lisa Brown',
      'Lisa B.',
      null,
      'Golf newbie looking for friendly faces to play with! More interested in laughs than birdies. Patient partners welcome!',
      'beginner',
      30.0,
      ARRAY['Casual Rounds', 'Social Networking', 'Skill Improvement'],
      ARRAY['meet new people', 'relax outdoors'],
      ARRAY['easygoing', 'supportive', 'encouraging'],
      'monthly',
      'afternoon',
      'relaxed',
      'right',
      'flexible',
      100,
      10,
      10,
      now(),
      now()
    ),
    (
      'cccccccc-cccc-cccc-cccc-cccccccccccc'::uuid,
      'kevin.lee@example.com',
      'Kevin Lee',
      'Kevin L.',
      null,
      'Fitness enthusiast who discovered golf. Love the mental and physical challenge. Always walk the course and keep a good pace.',
      'advanced',
      7.9,
      ARRAY['Weekend Warrior', 'Competitive Play', 'Skill Improvement'],
      ARRAY['stay active', 'sharpen skills'],
      ARRAY['competitive', 'energetic', 'disciplined'],
      'multiple_per_week',
      'morning',
      'fast',
      'left',
      'twosome',
      100,
      85,
      80,
      now(),
      now()
    ),
    (
      'dddddddd-dddd-dddd-dddd-dddddddddddd'::uuid,
      'amanda.martinez@example.com',
      'Amanda Martinez',
      'Amanda M.',
      null,
      'Improving steadily and loving the journey. Take lessons regularly and practice often. Looking for partners who enjoy working on their game.',
      'intermediate',
      17.2,
      ARRAY['Skill Improvement', 'Casual Rounds', 'Course Exploration'],
      ARRAY['sharpen skills', 'stay active'],
      ARRAY['focused', 'supportive', 'patient'],
      'weekly',
      'morning',
      'steady',
      'right',
      'threesome',
      100,
      42,
      40,
      now(),
      now()
    ),
    (
      'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'::uuid,
      'ryan.thompson@example.com',
      'Ryan Thompson',
      'Ryan T.',
      null,
      'Tech entrepreneur who uses golf for business and pleasure. Great conversations, strategic thinking, and building lasting relationships.',
      'advanced',
      8.1,
      ARRAY['Business Networking', 'Competitive Play', 'Social Networking'],
      ARRAY['host clients', 'meet new people'],
      ARRAY['strategic', 'confident', 'sociable'],
      'twice_per_month',
      'midday',
      'steady',
      'left',
      'twosome',
      100,
      95,
      90,
      now(),
      now()
    ),
    (
      'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid,
      'sophie.davis@example.com',
      'Sophie Davis',
      'Sophie D.',
      null,
      'Low handicap player who plays for the love of the game. Not into tournaments, just pure enjoyment. Happy to play with anyone who loves golf!',
      'expert',
      5.5,
      ARRAY['Casual Rounds', 'Course Exploration', 'Social Networking'],
      ARRAY['relax outdoors', 'mentor others'],
      ARRAY['supportive', 'patient', 'confident'],
      'weekly',
      'morning',
      'steady',
      'straight',
      'flexible',
      100,
      150,
      145,
      now(),
      now()
    )
  ON CONFLICT (id) DO NOTHING;

-- Recreate foreign key constraint with NOT VALID to allow existing mock profiles
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_id_fkey
  FOREIGN KEY (id) REFERENCES auth.users(id)
  ON DELETE CASCADE
  NOT VALID;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Note: New profiles created through the app will still be validated against auth.users
-- Only these pre-existing mock profiles are exempt from the constraint check
